name: build-hello-app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Get faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=TAG::latest-dev

      - name: Get Repo Owner
        id: get_repo_owner
        run: >
          echo ::set-output name=repo_owner::$(echo ${{github.repository_owner}} | tr
          '[:upper]' '[:lower]')

      - name: Docker Login
        run: >
          echo ${{secrets.DOCKER_PASSWORD}} |
          docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin

      - name: Publish functions
        run: >
          OWNER="${{steps.get_repo_owner.outputs.repo_owner}}"
          TAG="latest"
          faas-cli publish
          -f ${{secrets.FN_CONFIG_FILE}}
          --extra-tag ${{github.sha}}
          --platforms linux/amd64,linux/arm/v7,linux/arm64

      - name: Login openfaas
        run: >
          echo ${{secrets.OPENFAAS_PASSWORD}} |
          faas-cli login --gateway ${{secrets.OPENFAAS_URL}} --password-stdin

      - name: Deploy
        run: >
          OWNER="${{steps.get_repo_owner.outputs.repo_owner}}"
          TAG="${{github.sha}}"
          faas-cli deploy
          -f ${{secrets.FN_CONFIG_FILE}}
          --gateway ${{secrets.OPENFAAS_URL}}
